### ISSUE TITLE
Cannot compile under 4.15.3

### ISSUE THREAD

**Issue by HeadClot** [ArticySoftware/ArticyImporterForUnreal#1] opened 2017-09-19 04:56 UTC
Hey,
I am currently running into the following issues with the Articy Importer for Unreal. 

I am getting the following error from ArticyExpressoScripts.h at Line 144

>C4596	'AddDefinition': illegal qualified name in member declaration

I get this error twice then It fails to compile.

**Comment by nico-probst** [comment] 2017-09-20 09:17
Hi HeadClot,

can you try this with a completely new project and try to follow steps in the Readme exactly. This error sounds like one of the include paths from the unreal engine itself is not properly set as the only parameter of this method is of type  `FName`. Are you building unreal by code or are you using the epic launcher to get the engine? Without more information this sounds to me like an issue with your unreal installation. If possible you could upload the project for me and i try it on my computer.

Best regards
nico

**Comment by HeadClot** [comment] 2017-09-20 22:33
Here is the project that I am using for Unreal Engine 4. It is based on ue 4.15.3 Launcher version.

https://drive.google.com/open?id=0B5CHQtJBPq3iUnRvOFdfRHNRMFE

**Comment by nico-probst** [comment] 2017-09-21 09:42
Hi again,

thanks for the project. I triedit with my unreal engine version (*Version: 4.15.3-3450819+++UE4+Release-4.15*). I had to disable the "DonAINavigation" plugin as i don't have that. Created a new visual studio solution via the uproject file, rebuild the project from visual studio(2017) opened the project in ue and enabled the ArticyImporter plugin. I had no compile errors. Try disabling the "DonAINavigation" in the uproject and see if that fixes it. If not you might need to repair your unreal installation. What are you using to compile the c++ sources outside of the ue?

Best regards

Nico

**Comment by HeadClot** [comment] 2017-09-21 09:54
Hey @nico-probst - I am currently using VS 2017 to compile my UE4 Code projects. I have just Disabled 
the DonNavigation Plugin.

As for the UE4 Installation - I just downloaded UE 4.15.3 when I made this issue. So it is fresh to an extent.

**Comment by ash501** [comment] 2017-09-22 07:39
Hello @nico-probst,
I just tried compiling it too with a clean UE 4.17 version and run (besides a few others) into the same error,
It looks as if the problem is that you're overloading AddDefinition in the ArticyExpressoScripts.h while you're still in the struct definition. Currently, it says: 
_template<typename T>	static void ExpressoType::AddDefinition(const FName& CppType)_
if you change it to
_template<typename T>	static void AddDefinition(const FName& CppType)_
this part compiles.

Now I'm looking into some type conversations that are still failing due to multiple options to convert them.

So long and God bless you
Tobias

**Comment by HeadClot** [comment] 2017-09-22 07:41
Hey @peter-sabath - Thank you for the comment on this. Going to give this a shot.

**Comment by HeadClot** [comment] 2017-09-22 07:50
Thank you so much @ash501 ! I got it to compile under 4.15.3. :D 

Thank you so much!

**Comment by ash501** [comment] 2017-09-22 08:03
Great. You're welcome.

For 4.17 a few more changes are needed as explicity convert some types. With these changes the plugin compiles under 4.17

In ArticyObjectWithTarget.h change
virtual UArticyObject* SetSpeaker(UArticyObject* const Speaker)
	{
		SetSpeakerId(Speaker ? Speaker->GetId() : 0);
		return Speaker;
	}
to
virtual UArticyObject* SetSpeaker(UArticyObject* const Speaker)
	{
		SetSpeakerId(Speaker ? Speaker->GetId() : (FArticyId) 0);
		return Speaker;
	}
for the explicit conversion into the expected type.

Same in:
	virtual UArticyPrimitive* SetTarget(UArticyPrimitive* const Target)
	{
		SetTargetId(Target ? Target->GetId() : (FArticyId) 0);
		return Target;
	}
and (ArticyRef.cpp)
	void FArticyRef::SetReference(UArticyPrimitive* Object)
	{
		Reference = Object;
		SetId(Object ? Object->GetId() : (FArticyId) 0);
	}
It still shows a few warning about things that need to be changed for future versions of Unreal, but seems to be fine. I'll try testing it as soon as I can.

God bless you

**Comment by HeadClot** [comment] 2017-09-22 08:07
@ash501 If it is not too much to ask. Would it be possible to make a Pull Request? Just curious :)

**Comment by ash501** [comment] 2017-09-22 08:28
@HeadClot Let me check if I can remove the last warning as well and then I can see to make a Pull Request.

**Comment by HeadClot** [comment] 2017-09-22 08:28
Awesome!

**Comment by nico-probst** [comment] 2017-09-22 08:56
Thank you very much, @ash501. I still wonder why none of these showed up when i compile it here.

**Comment by HeadClot** [comment] 2017-09-22 08:59
@nico-probst [I think this is what you are looking for.](http://s2.quickmeme.com/img/03/031b11a5e7a6f752ddde008e257d1070c30e10ec1c7617d3ae1a309493d75f84.jpg)

Sorry I had too.

**Comment by ash501** [comment] 2017-09-22 10:53
Pull request is made and the files uploaded.
It now compiled without errors or warnings in UE 4.17

So long and God bless you

Tobias

**Comment by HeadClot** [comment] 2017-09-22 10:58
Thank you so much Tobias :)

**Comment by nico-probst** [comment] 2017-09-22 11:14
Thank you Tobias for your effort, you changes are merged.

best regards

Nico

**Closed by nico-probst** 2017-09-22 11:14 UTC
